-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.account
(
    userid integer NOT NULL DEFAULT nextval('subscribe_user_id_seq'::regclass),
    name text COLLATE pg_catalog."default",
    chatid numeric NOT NULL,
    status text COLLATE pg_catalog."default",
    joindate timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT account_chatid_pkey PRIMARY KEY (chatid)
);

CREATE TABLE IF NOT EXISTS public.bulletinraw
(
    id integer NOT NULL DEFAULT nextval('bulletinraw_id_seq'::regclass),
    publisher character varying(255) COLLATE pg_catalog."default",
    title character varying(255) COLLATE pg_catalog."default",
    url character varying(255) COLLATE pg_catalog."default",
    content text COLLATE pg_catalog."default",
    addtime timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT bulletinraw_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.subscription
(
    subscriptionid integer NOT NULL DEFAULT nextval('subscription_subscriptionid_seq'::regclass),
    chatid numeric,
    topicid integer,
    status character varying(20) COLLATE pg_catalog."default",
    notificationpreference character varying(20) COLLATE pg_catalog."default",
    joindate timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT subscription_pkey PRIMARY KEY (subscriptionid),
    CONSTRAINT unique_subscription_user_topic UNIQUE (chatid, topicid)
);

CREATE TABLE IF NOT EXISTS public.test
(
    id integer NOT NULL DEFAULT nextval('test_id_seq'::regclass),
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    addtime timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT test_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.topics
(
    topicid integer NOT NULL DEFAULT nextval('topics_topicid_seq'::regclass),
    topicname character varying(255) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    whocreate numeric,
    CONSTRAINT topics_pkey PRIMARY KEY (topicid)
);

ALTER TABLE IF EXISTS public.subscription
    ADD CONSTRAINT chatid_fkey FOREIGN KEY (chatid)
    REFERENCES public.account (chatid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.subscription
    ADD CONSTRAINT subscription_topicid_fkey FOREIGN KEY (topicid)
    REFERENCES public.topics (topicid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;