-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE SEQUENCE subscribe_user_id_seq;
CREATE SEQUENCE bulletinraw_id_seq;
CREATE SEQUENCE topics_topicid_seq;

CREATE TABLE IF NOT EXISTS public.account
(
    userid integer NOT NULL DEFAULT nextval('subscribe_user_id_seq'::regclass),
    name text COLLATE pg_catalog."default",
    chatid numeric NOT NULL,
    status text COLLATE pg_catalog."default",
    joindate timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT account_chatid_pkey PRIMARY KEY (chatid)
);

CREATE TABLE IF NOT EXISTS public.bulletinprocessed
(
    id serial NOT NULL,
    rawid integer,
    labelid integer,
    processedtime timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    sentstatus boolean NOT NULL DEFAULT false,
    CONSTRAINT bulletinprocessed_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.bulletinraw
(
    rawid integer NOT NULL DEFAULT nextval('bulletinraw_id_seq'::regclass),
    publisher character varying(255) COLLATE pg_catalog."default",
    title character varying(255) COLLATE pg_catalog."default",
    url character varying(255) COLLATE pg_catalog."default",
    content text COLLATE pg_catalog."default",
    addtime timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    processstatus boolean DEFAULT false,
    CONSTRAINT bulletinraw_pkey PRIMARY KEY (rawid)
);

CREATE TABLE IF NOT EXISTS public.coordinates
(
    id serial NOT NULL,
    function character varying(30) COLLATE pg_catalog."default",
    start integer NOT NULL,
    finish boolean NOT NULL DEFAULT false,
    addtime timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.label
(
    labelid integer NOT NULL DEFAULT nextval('topics_topicid_seq'::regclass),
    labelname character varying(255) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    whocreate numeric(20, 0),
    CONSTRAINT topics_pkey PRIMARY KEY (labelid)
);

CREATE TABLE IF NOT EXISTS public.subscription
(
    subscriptionid serial NOT NULL,
    chatid numeric,
    labelid integer,
    status character varying(20) COLLATE pg_catalog."default",
    notificationpreference character varying(20) COLLATE pg_catalog."default",
    joindate timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT subscription_pkey PRIMARY KEY (subscriptionid),
    CONSTRAINT unique_subscription_user_topic UNIQUE (chatid, labelid)
);

ALTER TABLE IF EXISTS public.bulletinprocessed
    ADD CONSTRAINT fk_rawid FOREIGN KEY (rawid)
    REFERENCES public.bulletinraw (rawid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bulletinprocessed
    ADD CONSTRAINT fk_topicid FOREIGN KEY (labelid)
    REFERENCES public.label (labelid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.subscription
    ADD CONSTRAINT chatid_fkey FOREIGN KEY (chatid)
    REFERENCES public.account (chatid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.subscription
    ADD CONSTRAINT subscription_topicid_fkey FOREIGN KEY (labelid)
    REFERENCES public.label (labelid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

INSERT INTO public.label (labelname, description, whocreate) VALUES
('餐點', '', 0),
('自我認識', '', 0),
('考試', '', 0),
('學習技能', '', 0),
('體育活動', '', 0),
('學校舉辦活動', '', 0),
('英文學分', '', 0),
('付費或繳款', '', 0),
('社會實踐', '', 1),
('機車車位', '', 1),
('獎助學金', '', 1),
('座談會', '', 1),
('演講', '', 1),
('工作坊', '', 1),
('選課時間', '', 1),
('行事曆發布', '', 1),
('停水', '', 1),
('停電', '', 1),
('斷網', '', 1),
('宿舍訊息', '', 1),
('禮卷', '', 1),
('抽獎', '', 1),
('實習機會', '', 1);
END;